samples = ["ERR13244179"]

rule all:
    input:
        expand("fastq/{sample}.fastq", sample=samples)

rule prefetch:
    params:
        outdir="sra/"
    output:
        directory("sra/{sample}")
    shell:
        "prefetch {wildcards.sample} -O {params.outdir}"

rule fasterq_dump:
    params:
        outdir="fastq/"
    input:
        "sra/{sample}/{sample}.sra"
    output:
        "fastq/{sample}.fastq"
    shell:
        "fasterq-dump {input} --outdir {params.outdir}"